# /*
#  * Copyright (c) 2024 IBM Corporation
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-svc
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraLabels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
    {{- range $i := untilStep (int .Values.devportal.clusterPorts.start) ( int .Values.devportal.clusterPorts.end) 1 }}
    - name: ignite-{{ $i }}
      port: {{ $i }}
      protocol: TCP
      targetPort: {{ $i }}
    {{- end }}
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.devportal.port }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8084
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{ include "common.labels.standard" . | nindent 4 }}
    {{- with .Values.extraLabels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.devportal.port }}
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8084
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP