apiVersion: v1
entries:
  apicontrolplane:
  - apiVersion: v2
    appVersion: "11.1"
    created: "2025-07-31T17:39:16.076254+02:00"
    dependencies:
    - name: common
      repository: https://ibm.github.io/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.0.3
    description: API Control Plane Helm Chart for Kubernetes
    digest: f265b65852766340b8a43b05bc79a742f4b6b643a4bbd8e0121e73ac3df13e44
    name: apicontrolplane
    type: application
    urls:
    - https://staillanibm.github.io/webmethods-helm-charts/charts/apicontrolplane-1.0.0.tgz
    version: 1.0.0
  apigateway:
  - apiVersion: v2
    appVersion: "11.1"
    created: "2025-07-31T17:39:16.078184+02:00"
    dependencies:
    - name: common
      repository: https://ibm.github.io/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.0.3
    - condition: prometheus-elasticsearch-exporter.enabled
      name: prometheus-elasticsearch-exporter
      repository: https://prometheus-community.github.io/helm-charts
      tags:
      - prometheus-elasticsearch-exporter
      version: 6.6.0
    description: API Gateway Helm Chart for Kubernetes
    digest: 87c3cbf8a3631c9872c8a0799403299ac4d323ba2f359faa47aefe0c643a51a4
    name: apigateway
    type: application
    urls:
    - https://staillanibm.github.io/webmethods-helm-charts/charts/apigateway-4.0.0.tgz
    version: 4.0.0
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 1.0.0
    created: "2025-07-31T17:39:16.07852+02:00"
    description: A Library Helm Chart for grouping common logic between IBM webMethods
      charts. This chart is not deployable by itself.
    digest: c498aa977406afdcbfd628746e52744d330f70277bd57cc2b086f47144f00259
    home: https://softwareag.com
    icon: https://softwareag.com/downloads/logos/softwareag-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - softwareag
    maintainers:
    - name: SoftwareAG
      url: https://softwareag.com
    name: common
    sources:
    - https://github.com/softwareag/webmethods-helm-charts
    type: library
    urls:
    - https://staillanibm.github.io/webmethods-helm-charts/charts/common-1.0.3.tgz
    version: 1.0.3
  developerportal:
  - apiVersion: v2
    appVersion: "11.1"
    created: "2025-07-31T17:39:16.079481+02:00"
    dependencies:
    - name: common
      repository: https://ibm.github.io/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.0.3
    - name: prometheus-elasticsearch-exporter
      repository: https://prometheus-community.github.io/helm-charts
      tags:
      - prometheus-elasticsearch-exporter
      version: 5.0.0
    description: webMethods Developer Portal Helm Chart for Kubernetes
    digest: 62632173ab3dd46268950c3b283286a7102eedaed319b0cce0ea8746516a99ed
    name: developerportal
    type: application
    urls:
    - https://staillanibm.github.io/webmethods-helm-charts/charts/developerportal-2.0.0.tgz
    version: 2.0.0
  microservicesruntime:
  - apiVersion: v2
    appVersion: "11.1"
    created: "2025-07-31T17:39:16.080174+02:00"
    dependencies:
    - name: common
      repository: https://ibm.github.io/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.0.2
    description: Microservices Runtime (MSR) Helm Chart for Kubernetes
    digest: fd5d32f39d0b44d71fdd6c8068c7f4792dea33f0ead2b536c879d4bd56dfabec
    name: microservicesruntime
    type: application
    urls:
    - https://staillanibm.github.io/webmethods-helm-charts/charts/microservicesruntime-2.0.0.tgz
    version: 2.0.0
  mywebmethodsserver:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2025-07-31T17:39:16.080707+02:00"
    dependencies:
    - name: common
      repository: https://ibm.github.io/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.0.3
    description: My webMethods Server (MWS) Helm Chart for Kubernetes
    digest: 93d57fd7a4041b8f380d4ddaf923d2fb3815382c9c10a8d01e87270a1576cf33
    name: mywebmethodsserver
    urls:
    - https://staillanibm.github.io/webmethods-helm-charts/charts/mywebmethodsserver-1.1.0.tgz
    version: 1.1.0
  terracottabigmemorymax:
  - apiVersion: v2
    appVersion: 4.4.0
    created: "2025-07-31T17:39:16.081159+02:00"
    dependencies:
    - name: common
      repository: https://ibm.github.io/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.0.3
    description: Terracotta BigMemory Max Helm Chart for Kubernetes
    digest: ef74df5739f1a91db8de3e149995be0b07d6d1cad3b79855ba109cd7861d53d0
    name: terracottabigmemorymax
    type: application
    urls:
    - https://staillanibm.github.io/webmethods-helm-charts/charts/terracottabigmemorymax-1.4.0.tgz
    version: 1.4.0
  universalmessaging:
  - apiVersion: v2
    appVersion: "10.15"
    created: "2025-07-31T17:39:16.081757+02:00"
    dependencies:
    - name: common
      repository: https://ibm.github.io/webmethods-helm-charts/charts
      tags:
      - softwareag-common
      version: 1.0.3
    description: Universal Messaging (UM) Helm Chart for Kubernetes
    digest: 5ab3c771d4a80abc758b96848a76d45e2fceacf0aa1085dcb8bbfa8a742effac
    name: universalmessaging
    type: application
    urls:
    - https://staillanibm.github.io/webmethods-helm-charts/charts/universalmessaging-1.0.7.tgz
    version: 1.0.7
generated: "2025-07-31T17:39:16.075552+02:00"
