apiVersion: v1
kind: Secret
metadata:
  name: msr-secrets
type: Opaque
stringData:
  # MSR Administrator password
  MSR_ADMIN_PASSWORD: "YourAdminPassword"

  # Keystore passwords for TLS certificates
  ADMIN_PORT_KEYSTORE_PASSWORD: "changeit"
  API_PORT_KEYSTORE_PASSWORD: "changeit"

  # Universal Messaging configuration
  UM_TRUSTSTORE_PASSWORD: "changeit"
  UM_URL: "nsps://um-server.your-namespace.svc.cluster.local:9443"
  UM_USERNAME: "your-um-user"
  UM_PASSWORD: "YourUMPassword"

  # Event Streams (Kafka) configuration
  ES_BOOTSTRAP_URL: "kafka-bootstrap.your-namespace.svc.cluster.local:9093"
  ES_USERNAME: "your-kafka-user"
  ES_PASSWORD: "YourKafkaPassword"
  ES_TRUSTSTORE_PASSWORD: "changeit"

---

apiVersion: v1
kind: Secret
metadata:
  name: event-streams-tls
type: Opaque
data:
  # Base64 encoded PKCS12 certificate for Event Streams (Kafka) TLS connection
  # To create: base64 -i your-kafka-cert.p12 | tr -d '\n'
  es-cert.p12: <base64-encoded-p12-certificate>
